// 5. Write multithreaded program that generates the Fibonacci series. The program
// should work as follows: The user will enter on the command line the number of
// Fibonacci numbers that the program is to generate. The program then will create
// a separate thread that will generate the Fibonacci numbers, placing the sequence
// in data that is shared by the threads (an array is probably the most convenient
// data structure). When the thread finishes execution the parent will output the
// sequence generated by the child thread. Because the parent thread cannot begin
// outputting the Fibonacci sequence until the child thread finishes, this will require
// having the parent thread wait for the child thread to finish.
#include <bits/stdc++.h>
#include <sys/wait.h>
#include <chrono> 
using namespace std;
using namespace chrono;
vector<long long> fib;
int n;

void* generateFibonacci(void*) {
    if (n >= 1) fib[0] = 0;
    if (n >= 2) fib[1] = 1;

    for (int i = 2; i < n; i++)
        fib[i] = fib[i - 1] + fib[i - 2];

    pthread_exit(NULL);
}

int main(int argc, char* argv[]) {
    if (argc < 2) return 1;

    n = stoi(argv[1]);
    fib.resize(n);

    pthread_t thread;
    pthread_create(&thread, NULL, generateFibonacci, NULL);

    pthread_join(thread, NULL);

    for (int i = 0; i < n; i++)
        cout << fib[i] << " ";
    cout << endl;

    return 0;
}

